
default: &default
  adapter: postgresql
  encoding: unicode
  username: satoshy
  password: qwerty
  pool: 5
  host: localhost

development:
  <<: *default
  database: rails_api_development

test:
  <<: *default
  database: rails_api_test

production:
  <<: *default
  database: rails_api_production
  username: rails_api
  password: <%= ENV['RAILS_API_DATABASE_PASSWORD'] %>
