# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f0148758e3f0fa3d22de390884b08b36cd085148fa138d4a3908c2f6543b861931d455bebc45ab384b3a3e485c82c6ac066e5bb026504be085204da3ed24b81

test:
  secret_key_base: 5193e86ce042e6601b7b94912a4f51e98c3c63d9032852bc76fd167787117d8b66d7499c614c95b3c751369c888c772ac7ecc4e9570cc0141df9e87479522db7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
